version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-node-app .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 597088043946.dkr.ecr.ap-south-1.amazonaws.com
      - docker tag my-node-app:latest 597088043946.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:latest
      - docker push 597088043946.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:latest
artifacts:
  files:
    - "**/*"
  base-directory: build-output
  discard-paths: yes
  name: BuildArtif
